trigger:
  branches:
    include:
      - main

pool:
  name: AgentsDevops
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    docker version
  displayName: 'Validar version de Docker'

- script: |
    echo "Creando nueva imagen miapp:1 ..."
    docker compose build    
  displayName: 'Crear imagen de Docker'

- script: |
    docker images
  displayName: 'Validar imágenes de Docker'

- script: |
    echo "Creando red mired, contenedores my_mongo y my_node..."
    docker compose up -d
  displayName: 'Crear red mired, contenedores my_mongo y my_node...'

- script: |
    echo "Ejecutando tests..."
    if [ "$(docker ps -q -f name=my_node)" ]; then
        docker exec my_node npm test
    else
        echo "El contenedor my_node no está en ejecución. Abortando tests."
        exit 1
    fi
  displayName: 'Run Node.js tests'

- script: |
    echo "Limpiando recursos..."
    docker compose down
  displayName: 'Limpiar recursos'

