apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node
  template:
    metadata:
      labels:
        app: my-node
    spec:
      containers:
      - name: my-node
        image: miapp:1
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "acervantes"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mongo
  template:
    metadata:
      labels:
        app: my-mongo
    spec:
      containers:
      - name: my-mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "acervantes"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: my-node
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
  selector:
    app: my-node
---
apiVersion: v1
kind: Service
metadata:
  name: my-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: my-mongo
